#使用外部tomcat，就不需要配置这个了
#server:
#  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogproject_test?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123

mybatis-plus:
  type-aliases-package: my.lxh.blog.entity
  global-config:
    db-config:
      table-prefix: t_
      id-type: auto
    banner: false


logging:
  level:
    my.lxh.blog.mapper: debug
